publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: lunohq/luno-web
    tag:
      - latest
      - $$COMMIT

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: ops
