build:
  image: node:5.10.1
  commands:
    - mv /drone/dev_deps node_modules || true
    - npm install
    - make release -j
    - mv node_modules /drone/dev_deps
    - mv /drone/server_deps node_modules || true
    - npm install --production
    - cp -a node_modules /drone/server_deps/
  environment:
    - S3_BUCKET=luno-web
    - S3_REGION=us-east-1

cache:
  mount:
    - /drone/dev_deps
    - /drone/server_deps
    - .git

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: lunohq/luno-web
    tag:
      - latest
      - $$COMMIT

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: ops
    template: >
      *{{ build.status }}* <{{ system.link_url }}/{{ repo.full_name }}/{{ build.number }}|{{ repo.owner }}/{{ repo.name }}#{{ build.commit[:8] }}> ({{ build.branch }}) by {{ build.author }}\\n*Deploy With:*```emp deploy {{ repo.owner }}/{{ repo.name }}:{{ build.commit }}```
