publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: lunohq/luno-web
    tag:
      - latest
      - $$COMMIT

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: ops
